name: Tests_Workflow

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      APP_PORT: 3000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: example_db
      DB_USER: root
      DB_PASS: example
      JWT_EXPIRES_IN_SECONDS: 3600
      JWT_PUBLIC_KEY_BASE64: ${{secrets.JWT_PUBLIC_KEY_BASE64}}
      JWT_PRIVATE_KEY_BASE64: ${{secrets.JWT_PRIVATE_KEY_BASE64}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d mysqldb
      - name: Check running containers
        run: docker ps -a
      - name: Run e2e tests
        run: sleep 5 && npm run test:e2e

name: Build_Workflow

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Run build step
        run: npm run build
